### PR TITLE
fix: handle parcel content initialization failure

### LINKED ISSUE #339: Add fallback Root CID for parcels where the Ceramic stream doesn't get initialized
**Description**
While testing the latest build on OP Goerli, my first two parcel claims were made before a DNS change for our Ceramic node had propagated. The result was that the Ceramic Stream wasn't initiated at the claim and there is no subsequent Root CID to be found.

If no Root CID exists, rather than showing a spinner infinitely we should display "Not Available". 

Cody is separately taking a look at the way that this issue would be resolved with the Ceramic Stream being initialized with subsequent actions.

Screenshot 2022-12-13 at 4 07 22 PM

### PR DESCRIPTION
**Pull request by tnrdd**
# Description

Check if there was an initialisation failure by checking if the `@geo-web/content` library method `resolveRoot` returns an empty object and if so show a "Not Available" message instead of the Root CID in the parcel info panel.
If there was an initialisation failure the media gallery must be initialised before adding content, this is done in the `useMediaGallery` custom hook.

# Issue

fixes #339 

# Checklist:

- [x] My commit message follows the Conventional Commits specification
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested my code
- [x] My changes generate no new warnings
- [x] My PR is rebased off the most recent `develop` branch
- [x] My PR is opened against the `develop` branch

# Alert Reviewers

@codynhat @gravenp

### CODE REVIEW

File: components/cards/ActionForm.tsx [hunk 1]
```diff
@@ -276,8 +276,12 @@ export function ActionForm(props: ActionFormProps) {
         parcelId: assetId,
         ownerId,
       });
+      const root = await geoWebContent.raw.getPath("/", {
+        parcelId: assetId,
+        ownerId,
+      });
 
-      setRootCid(newRootCid.toString());
+      setRootCid(root?.basicProfile ? newRootCid.toString() : null);
```
Comment (codynhat) [inline components/cards/ActionForm.tsx:284]: What if `mediaGallery` exists but `basicProfile` doesn't? We should assume other Cadastres can make writes that we don't know about.

**Review by gravenp — APPROVED** [review]
Looking good on my end with the formerly bricked parcels. basicProfile & mediaGallery accepting edits.

@codynhat ready for you

File: components/cards/ActionForm.tsx (hunk 1 above)
Comment (codynhat) [reply components/cards/ActionForm.tsx:284]: It's unclear to me from looking at the code below what a missing `basicProfile` but an existing `mediaGallery` would do.

**Review by codynhat — CHANGES_REQUESTED** [review]

File: components/cards/ActionForm.tsx (hunk 1 above)
Comment (tnrdd) [reply components/cards/ActionForm.tsx:284]: If `basicProfile` is not defined here it means `resolveRoot` returned a CID pointing to an empty object because the edit failed.
By setting `rootCid` to null we show a "Not Available" message and the user can retry to edit later on while preserving the `/mediaGallery` path, otherwise if we check if the media gallery exists here the root CID would just point to an empty object.

Comment (codynhat) [reply components/cards/ActionForm.tsx:284]: The root CID would not be an empty object if `/mediaGallery` exists, but `rootCid` would still be set to null here in that case.

Comment (tnrdd) [reply components/cards/ActionForm.tsx:284]: Oh right, but I think `basicProfile` would be defined too because it was just edited and committed.
We can check for it anyway for clarity and to be sure.

Comment (codynhat) [reply components/cards/ActionForm.tsx]: Right, that is if the content was created with this Cadastre. But this is more about being interoperable with other cadastres. The schema allows for only one of them to exist.

**Review by codynhat — APPROVED** [review]

File: components/cards/ActionForm.tsx (hunk 1 above)
Comment (tnrdd) [reply components/cards/ActionForm.tsx]: Yes now I get it what you mean before, thanks.
