### PR TITLE
fix: add signer to reclaim contract call

### LINKED ISSUE #258: Reclaim/foreclosure transactions are failing due to no/incorrect signer
**Describe the bug**
When reclaiming a parcel (wallet was the previous licensor) or making a foreclosure claim (wallet is not the previous licensor), I'm getting an error message that reads "Error: sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.7.0)".  Ex screenshot:

Screen Shot 2022-10-10 at 9 26 29 AM

Per Cody, regression might have been introduced when he was making adjustments to limit excessive RPC calls.

### PR DESCRIPTION
**Pull request by tnrdd**
# Description

Connect the signer to the license diamond contract.

# Issue

fixes #258

# Checklist:

- [x] My commit message follows the Conventional Commits specification
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested my code
- [x] My changes generate no new warnings
- [x] My PR is rebased off the most recent `develop` branch
- [x] My PR is opened against the `develop` branch

# Alert Reviewers

@codynhat @gravenp

### CODE REVIEW

**Review by gravenp — APPROVED** [review]
Both reclaims and foreclosure bids were processed correctly. 

@codynhat this ready for your review.

File: components/cards/ParcelInfo.tsx [hunk 1]
```diff
@@ -214,31 +214,6 @@ function ParcelInfo(props: ParcelInfoProps) {
     loadLicenseDiamond();
   }, [licenseDiamondAddress, sfFramework, paymentToken]);
 
-  React.useEffect(() => {
```
Comment (codynhat) [inline components/cards/ParcelInfo.tsx:217]: Is this a duplicate of above? Must be from a bad merge.

**Review by codynhat — APPROVED** [review]

File: components/cards/ParcelInfo.tsx (hunk 1 above)
Comment (tnrdd) [reply components/cards/ParcelInfo.tsx:217]: Yes it's doing the same things minus last few lines.
Maybe was left there on merge because it didn't conflict.
